[project]
name = "govuk-chat-v2-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = []

[tool.uv.workspace]
members = [
    "services/chat-api-fastapi",
    "services/example-agent",
    "services/agui-agent",
    "libs/python/*",
]

[tool.uv.sources]
agent-runtime-types = { workspace = true }

[tool.pyright]
ignore = [
    "**/build"
]
