[project]
name = "example-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "agent-runtime-types",
    "aws-opentelemetry-distro>=0.18.0",
    "bedrock-agentcore>=1.18.1",
    "govuk-chat-v2-prototype-private",
    "strands-agents>=1.47.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.2",
]

[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src"
]

[tool.uv.sources]
govuk-chat-v2-prototype-private = { git = "https://github.com/govuk-once/govuk-chat-v2-prototype-private.git" }
